/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course;

import dao.ImplementTeacher;
import dao.TeacherDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Teachers;

/**
 *
 * @author revanthane
 */
public class FormTeacher extends javax.swing.JFrame {

    /**
     * Creates new form FormTeacher
     */
    public FormTeacher() {
        initComponents();
        loadTable("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherLabel = new javax.swing.JLabel();
        txtTeacher = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deketeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teacherLabel.setText("Teacher Name");

        txtTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherActionPerformed(evt);
            }
        });

        idLabel.setText("0");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deketeBtn.setText("Delete");
        deketeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deketeBtnActionPerformed(evt);
            }
        });

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacherTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherLabel)
                            .addComponent(saveBtn))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(idLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(42, 42, 42)
                                .addComponent(deketeBtn)))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherLabel)
                    .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn)
                    .addComponent(deketeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherActionPerformed

    private void clearData(){
        txtTeacher.setText("");
    }
    DefaultTableModel tbteacher;
    private void loadTable(String search){
        tbteacher = new DefaultTableModel();
        tbteacher.addColumn("id");
        tbteacher.addColumn("name");
        ImplementTeacher imp = new TeacherDao();
        List<Teachers> listteacher;
        if (search.equals("")){
            listteacher = imp.getAllData();
        } else {
            listteacher= imp.getSearch(search);
        }
        for (Teachers element : listteacher){
            tbteacher.addRow(new Object[]{element.getTeacherId(), element.getTeacherName()});
        }
        teacherTable.setModel(tbteacher);
    }
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        ImplementTeacher imp = new TeacherDao();
        Teachers teacher = new Teachers();
        teacher.setTeacherName(txtTeacher.getText());
        
        
        imp.insert(teacher);
        clearData();
        
        loadTable("");
          
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        ImplementTeacher imp = new TeacherDao();
        Teachers teacher = new Teachers();
        teacher.setTeacherName(txtTeacher.getText());
        teacher.setTeacherId(Integer.parseInt(idLabel.getText()));
        
        imp.update(teacher);
        clearData();
        
        loadTable("");
          
        
        
    }//GEN-LAST:event_updateBtnActionPerformed

    
    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        // TODO add your handling code here:
        int bar = teacherTable.getSelectedRow();
        String id = tbteacher.getValueAt (bar, 0).toString();
        String name = tbteacher.getValueAt (bar,1).toString();

        idLabel.setText(id);
        txtTeacher.setText(name);
    }//GEN-LAST:event_teacherTableMouseClicked

    private void deketeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deketeBtnActionPerformed
        // TODO add your handling code here:
        
        ImplementTeacher imp = new TeacherDao();
        Teachers teacher = new Teachers();
        teacher.setTeacherName(txtTeacher.getText());
        teacher.setTeacherId(Integer.parseInt(idLabel.getText()));
        
        imp.delete(teacher);
        clearData();
        
        loadTable("");
    }//GEN-LAST:event_deketeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deketeBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JTable teacherTable;
    private javax.swing.JTextField txtTeacher;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
